# Generated by Django 3.2.16 on 2023-07-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_alter_projects_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='address',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='github',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='personalinformation',
            name='twitter',
        ),
        migrations.AlterField(
            model_name='about',
            name='about_avatar',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='personalinformation',
            name='avatar',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
