# Generated by Django 3.2.16 on 2023-07-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_auto_20230711_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='num',
        ),
        migrations.AddField(
            model_name='skills',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
