# Generated by Django 3.2.16 on 2023-07-11 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0007_rename_linkedin_blogs_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='location',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='link',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='msg',
        ),
    ]
