# Generated by Django 3.2.16 on 2023-07-12 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_auto_20230712_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinformation',
            name='avatar',
        ),
    ]
