# Generated by Django 3.2.16 on 2023-07-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_remove_personalinformation_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinformation',
            name='avatar',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
