# Generated by Django 3.2.16 on 2023-07-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_personalinformation_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='medium',
            field=models.URLField(blank=True, null=True),
        ),
    ]
